In [59]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder,StandardScaler,PowerTransformer
from lightgbm import LGBMClassifier
from sklearn.pipeline import make_pipeline
from sklearn.compose import make_column_transformer
from sklearn.model_selection import KFold, cross_val_predict, train_test_split,GridSearchCV,cross_val_score
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

####
from sklearn.model_selection import KFold,cross_val_score, RepeatedStratifiedKFold,StratifiedKFold
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.preprocessing import OneHotEncoder,StandardScaler,PowerTransformer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.impute import SimpleImputer
from sklearn.dummy import DummyClassifier

from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.neighbors import KNeighborsClassifier

from lightgbm import LGBMClassifier

from sklearn.pipeline import make_pipeline
from sklearn.pipeline import Pipeline
from sklearn.compose import make_column_transformer

from sklearn.model_selection import KFold, cross_val_predict, train_test_split,GridSearchCV,cross_val_score
from sklearn.metrics import accuracy_score,classification_report

import plotly.offline

import plotly 
import plotly.express as px
import plotly.graph_objs as go
import plotly.offline as py
from plotly.offline import iplot
from plotly.subplots import make_subplots
import plotly.figure_factory as ff

import warnings
warnings.filterwarnings("ignore")


In [ ]:
# docker run -it --rm -p 8888:8888 -p 3000:3000 bentoml/quickstart:latest

In [60]:
def train_model_without_pipeline():
    print("2. Entrenando Modelo")
    df = pd.read_csv('heart.csv')
    numerical= df.drop(['HeartDisease'], axis=1).select_dtypes('number').columns
    categorical = df.select_dtypes('object').columns
    y = df['HeartDisease']
    X= df.drop('HeartDisease', axis=1)
    y= df['HeartDisease']
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
    ohe= OneHotEncoder()
    ct= make_column_transformer((ohe,categorical),remainder='passthrough')  
    model=LGBMClassifier(random_state=0)
    # pipe = make_pipeline(ct, model)
    # pipe.fit(X_train, y_train)
    X_train=ct.fit_transform(X_train)
    model.fit(X_train, y_train)
    return pipe

In [61]:
def train_model():
    print("2. Entrenando Modelo")
    df = pd.read_csv('heart.csv')
    numerical= df.drop(['HeartDisease'], axis=1).select_dtypes('number').columns
    categorical = df.select_dtypes('object').columns
    y = df['HeartDisease']
    X= df.drop('HeartDisease', axis=1)
    y= df['HeartDisease']
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
    ohe= OneHotEncoder()
    ct= make_column_transformer((ohe,categorical),remainder='passthrough')  
    model=LGBMClassifier(random_state=0)
    pipe = make_pipeline(ct, model)
    pipe.fit(X_train, y_train)

    return pipe

In [62]:
pipe=train_model()

2. Entrenando Modelo


In [103]:
#PREDICTING REAL VALUES
ga = bentoml.sklearn.get("my_beauty_model:latest").to_runner()
ga.init_local()
df = pd.read_csv('heart.csv')
numerical= df.drop(['HeartDisease'], axis=1).select_dtypes('number').columns
categorical = df.select_dtypes('object').columns
y = df['HeartDisease']
X= df.drop('HeartDisease', axis=1)
y= df['HeartDisease']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
model_names = ['LightGBM']
accuracy =[]
y_pred = pipe.predict(X_test)
y_pred

'Runner.init_local' is for debugging and testing only


array([0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0], dtype=int64)

In [50]:
import bentoml
from sklearn import pipeline

# ga = bentoml.sklearn.get("my_beauty_model:latest").to_runner()
# ga.init_local()

ga = bentoml.sklearn.load_model("my_beauty_model:latest")

In [63]:
### Predicting Proba

df = pd.read_csv('heart.csv')
numerical= df.drop(['HeartDisease'], axis=1).select_dtypes('number').columns
categorical = df.select_dtypes('object').columns
y = df['HeartDisease']
X= df.drop('HeartDisease', axis=1)
y= df['HeartDisease']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
model_names = ['LightGBM']
accuracy =[]
y_pred = pipe.predict_proba(X_test)

In [65]:
# y_pred

In [124]:
### CREATING NEW RUNNER
### RESOURCES:
# https://docs.bentoml.org/en/latest/concepts/runner.html
# https://scikit-learn.org/stable/modules/generated/sklearn.pipeline.Pipeline.html#sklearn.pipeline.Pipeline.predict_proba
# https://machinelearningmastery.com/columntransformer-for-numerical-and-categorical-data/
from typing import Any
import bentoml
from bentoml.io import JSON
from bentoml.io import NumpyNdarray, PandasDataFrame
import pandas as pd
import numpy as np

bento_model = bentoml.sklearn.get("my_beauty_model:latest")

#https://www.geeksforgeeks.org/python-get-first-element-of-each-sublist/
def Extract(lst):
    return [item[-1] for item in lst]

class Heartpredict(bentoml.Runnable):
    # SUPPORTED_RESOURCES = ("cpu",)
    # SUPPORTS_CPU_MULTI_THREADING = True

    def __init__(self):
        # load the model instance
        self.model = bentoml.sklearn.load_model("my_beauty_model:latest")

    @bentoml.Runnable.method(batchable=False)
    def predict_proba(self, input_data):
        return self.model.predict_proba(input_data)

heart_predict_runner = bentoml.Runner(Heartpredict, models=[bento_model])
heart_predict_runner.init_local()
# svc = bentoml.Service("heart_disease_predictor", runners=[heart_predict_runner])


# @svc.api(input=PandasDataFrame(), output=NumpyNdarray())
# def predict(df: pd.DataFrame) -> np.ndarray:
#     results = heart_predict_runner.predict_proba.run(df)
#     return Extract(results)

    

Using lowercased runnable class name 'heartpredict' for runner.
'Runner.init_local' is for debugging and testing only


In [125]:
df = pd.read_csv('heart.csv')
numerical= df.drop(['HeartDisease'], axis=1).select_dtypes('number').columns
categorical = df.select_dtypes('object').columns
y = df['HeartDisease']
X= df.drop('HeartDisease', axis=1)
y= df['HeartDisease']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
model_names = ['LightGBM']
accuracy =[]

In [126]:
heart_predict_runner.predict_proba.run(X_test)

array([[9.87126398e-01, 1.28736024e-02],
       [2.24421330e-02, 9.77557867e-01],
       [1.39404621e-02, 9.86059538e-01],
       [6.88028578e-03, 9.93119714e-01],
       [9.48121581e-01, 5.18784188e-02],
       [5.35926939e-01, 4.64073061e-01],
       [9.29163302e-02, 9.07083670e-01],
       [8.37159015e-01, 1.62840985e-01],
       [7.44406044e-01, 2.55593956e-01],
       [3.49855566e-02, 9.65014443e-01],
       [5.36445024e-01, 4.63554976e-01],
       [9.82599687e-01, 1.74003131e-02],
       [1.62881648e-01, 8.37118352e-01],
       [9.87398877e-01, 1.26011228e-02],
       [1.66212859e-02, 9.83378714e-01],
       [3.17231407e-01, 6.82768593e-01],
       [9.77839557e-01, 2.21604430e-02],
       [1.41938893e-01, 8.58061107e-01],
       [2.21648958e-01, 7.78351042e-01],
       [7.82053426e-01, 2.17946574e-01],
       [5.89092836e-02, 9.41090716e-01],
       [1.03925381e-01, 8.96074619e-01],
       [9.98569457e-01, 1.43054344e-03],
       [7.09332378e-01, 2.90667622e-01],
       [7.742170

In [74]:
X_test

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
668   63   F           ATA        140          195          0     Normal   
30    53   M           NAP        145          518          0     Normal   
377   65   M           ASY        160            0          1         ST   
535   56   M           ASY        130            0          0        LVH   
807   54   M           ATA        108          309          0     Normal   
..   ...  ..           ...        ...          ...        ...        ...   
133   56   M           ASY        150          230          0         ST   
813   69   F            TA        140          239          0     Normal   
734   56   M           ASY        130          283          1        LVH   
360   62   M           NAP        160            0          0     Normal   
875   58   F           NAP        120          340          0     Normal   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  
668    179              N      0.0       Up  
30     130              N      0.0     Flat  
377    122              N      1.2     Flat  
535    122              Y      1.0     Flat  
807    156              N      0.0       Up  
..     ...            ...      ...      ...  
133    124              Y      1.5     Flat  
813    151              N      1.8       Up  
734    103              Y      1.6     Down  
360     72              Y      0.0     Flat  
875    172              N      0.0       Up  

[276 rows x 11 columns]

In [109]:
ga=[63,"F","ATA",140,195,0,"Normal",179,"N",0.0,"Up"]
# ga=ga.reshape(1, -1)
# ga={"Age":63,"Sex":"F","ChestPainType":"ATA","RestingBP":140,"Cholesterol":195,"FastingBS":0,"RestingECG":"Normal","MaxHR":179,"ExerciseAngina":"N","Oldpeak":0.0,"ST_Slope":"Up"}
ga

[63, 'F', 'ATA', 140, 195, 0, 'Normal', 179, 'N', 0.0, 'Up']

In [114]:
df = pd.DataFrame([ga],columns=X_test.columns)
df

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   63   F           ATA        140          195          0     Normal    179   

  ExerciseAngina  Oldpeak ST_Slope  
0              N      0.0       Up

In [83]:
X_test.columns

Index(['Age', 'Sex', 'ChestPainType', 'RestingBP', 'Cholesterol', 'FastingBS',
       'RestingECG', 'MaxHR', 'ExerciseAngina', 'Oldpeak', 'ST_Slope'],
      dtype='object')

In [111]:
heart_predict_runner.predict_proba.run(df)

array([[0.9871264, 0.0128736]])

In [112]:
def Extract(lst):
    return [item[-1] for item in lst]

In [113]:
Extract(heart_predict_runner.predict_proba.run(df))

[0.012873602441079279]

In [2]:
import requests
prediction=requests.post(
    "http://localhost:3000/predict",
    headers={"content-type": "application/json"},
    data='{"Age":63,"Sex":"F","ChestPainType":"ATA","RestingBP":140,"Cholesterol":195,"FastingBS":0,"RestingECG":"Normal","MaxHR":179,"ExerciseAngina":"N","Oldpeak":0.0,"ST_Slope":"Up"}').text

print(prediction)

0.012873602441079279


In [10]:
import requests
prediction=requests.post(
    "https://heart-disease-predictor-imagen-ioqjxmu3cq-uc.a.run.app/predict",
    headers={"content-type": "application/json"},
    data='{"Age":63,"Sex":"F","ChestPainType":"ATA","RestingBP":140,"Cholesterol":195,"FastingBS":0,"RestingECG":"Normal","MaxHR":179,"ExerciseAngina":"N","Oldpeak":0.0,"ST_Slope":"Up"}').text

print(prediction)

0.012873602441079279


In [73]:
#Last test
def Extract(lst):
    return [item[-1] for item in lst][0]*100
    
Extract([[0.9871264, 0.1445445]])

14.45445

In [16]:
round(0.019,2)

0.02